apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: app1-main
      imagePullPolicy: Always
      imageRegistry: docker.io/app1
      imagePullSecretName: imagepull-docker
      credentialId: credential_3ecc19c0-ace1-420a-a694-80a2fd1d590f
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: app1
    version: v1.0.0
    applicationId: app_aa9ea4b3-c760-42a7-b4c0-c0e85d44edd5
    projectId: project_2114d41b-c03c-493c-9940-7a11fce4f083
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_40bd25fa-325e-4119-95cf-3916c73fee34
    environmentName: dev1
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: app1
  serviceType: ClusterIP
  version: v1.0.0
  namespace: test-ns
