apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: promotheus-dev1
  namespace: test-jayani-dev
spec:
  interval: 1m0s
  url: https://github.com/JayaniJ00/test-service-project
  ref:
    branch: master
  secretRef:
    name: promotheus-dev1
  timeout: 60s
