apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: app-new-new-v1-0-0
    applicationId: app_e6c7c5da-5454-41cd-b9fe-acb15343138b
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_2114d41b-c03c-493c-9940-7a11fce4f083
    environmentId: env_f9af21bc-4e43-4d13-ad38-eee9ca5e0004
  name: app-new-new-v1-0-0
spec:
  selector:
    app: app-new-new-v1-0-0
