apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mm
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_2114d41b-c03c-493c-9940-7a11fce4f083
    environmentId: env_43ca95d8-7ff2-4f86-bc6f-349495bc3960
    m: mmm
  mm: '89'
spec:
  groups:
    - name: ''
      rules:
        - alert: ''
          expr: ''
          annotations:
            summary: ''
            description: ''
          labels:
            '': ''
