apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: test999-main
      imagePullPolicy: Always
      imageRegistry: jayani00/https://github.com/JayaniJ00
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: test999
    version: v1.0.0
    projectId: project_2114d41b-c03c-493c-9940-7a11fce4f083
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_40bd25fa-325e-4119-95cf-3916c73fee34
    environmentName: dev1
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: test999
  serviceType: ClusterIP
  version: v1.0.0
  namespace: test-ns
