apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: application-main
      imagePullPolicy: Always
      imageRegistry: docker.io/application
      imagePullSecretName: imagepull-docker
      credentialId: credential_3ecc19c0-ace1-420a-a694-80a2fd1d590f
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: application
    version: v1.0.0
    applicationId: app_361b5d87-657e-473b-bb24-8df29829aec2
    projectId: project_2114d41b-c03c-493c-9940-7a11fce4f083
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_f82038a9-37d8-463a-b8ae-3a397f981115
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: application
  serviceType: ClusterIP
  version: v1.0.0
  namespace: test-jayani-staging
