apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 80
          targetPort: 80
          protocol: TCP
      healthChecks: []
      name: s1-main
      imagePullPolicy: Always
      imageRegistry: docker.io/s1
      imagePullSecretName: imagepull-docker
      credentialId: credential_3ecc19c0-ace1-420a-a694-80a2fd1d590f
    - name: container1
      imagePullPolicy: Always
      imageRegistry: jay/
      applicationPorts: []
      cpuRequestMili: 100
      cpuLimitMili: 2000
      memoryRequestMb: 100
      memoryLimitMb: 1000
      command: []
      args: []
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: s1
    version: v1.0.0
    applicationId: app_0371aea6-c32b-4157-bc43-d9ef3853b024
    projectId: project_2114d41b-c03c-493c-9940-7a11fce4f083
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_43ca95d8-7ff2-4f86-bc6f-349495bc3960
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: s1
  serviceType: ClusterIP
  version: v1.0.0
  namespace: test-jayani-dev
