apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: 14613e8a78a3fb9154d1913bafaedba2441e0551
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks:
        - probeType:
            - readinessProbe
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 30
          httpGet:
            path: /health
            port: 80
            httpHeaders: []
        - probeType:
            - livenessProbe
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 30
          tcpSocket:
            port: 80
        - probeType:
            - startupProbe
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 9
          tcpSocket:
            port: 80
      name: application-main
      imagePullPolicy: Always
      imageRegistry: jayani00/application
      imagePullSecretName: imagepull-docker
      credentialId: credential_3ecc19c0-ace1-420a-a694-80a2fd1d590f
      commitDetails:
        commitHash: 14613e8a78a3fb9154d1913bafaedba2441e0551
        commitAvatar: https://github.com/skyu-v2-dev[bot].png
        commitTime: '2024-12-08T11:16:58Z'
        commitMessage: Deploy application to dev
        commitUser: skyu-v2-dev[bot]
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: application
    version: v1.0.0
    applicationId: app_361b5d87-657e-473b-bb24-8df29829aec2
    projectId: project_2114d41b-c03c-493c-9940-7a11fce4f083
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_43ca95d8-7ff2-4f86-bc6f-349495bc3960
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: application
  serviceType: ClusterIP
  version: v1.0.0
  namespace: test-jayani-dev
