apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: application-v1-0-0
  labels:
    app: application-v1-0-0
    applicationId: app_361b5d87-657e-473b-bb24-8df29829aec2
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_2114d41b-c03c-493c-9940-7a11fce4f083
    environmentId: env_43ca95d8-7ff2-4f86-bc6f-349495bc3960
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application-v1-0-0
