openapi: 3.0.0
info:
  title: User Login API
  version: 1.0.0
  description: API for user login functionality
paths:
  /login:
    post:
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
        '404':
          description: User not found
        '500':
          description: Internal server error
servers:
  - url: https://api.example.com/v1