apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers: []
  name: helm3
  type: HelmChart
  horizontalAutoScalingRules: []
  volumes: []
  version: v1.0.0
  labels:
    app: helm3
    version: v1.0.0
    applicationId: app_b7178e21-f7c6-4615-b5b3-d20d18a8ca26
    projectId: project_2114d41b-c03c-493c-9940-7a11fce4f083
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_f9af21bc-4e43-4d13-ad38-eee9ca5e0004
    environmentName: prod
  namespace: test-jayani-prod
